
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Aug 17 23:53:14 EDT 2016
//----------------------------------------------------

package formula.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FORALL = 19;
  public static final int STR = 41;
  public static final int EMPTY = 38;
  public static final int UMINUS = 15;
  public static final int LPAREN = 30;
  public static final int MINUS = 14;
  public static final int RPAREN = 29;
  public static final int NOT = 4;
  public static final int AND = 2;
  public static final int SETDEF = 26;
  public static final int LT = 10;
  public static final int NIN = 23;
  public static final int IN = 22;
  public static final int OR = 3;
  public static final int COMMA = 34;
  public static final int DIV = 18;
  public static final int GEQ = 11;
  public static final int NUM = 39;
  public static final int PLUS = 13;
  public static final int ID = 40;
  public static final int DOT = 33;
  public static final int EOF = 0;
  public static final int TRUE = 36;
  public static final int error = 1;
  public static final int MUL = 16;
  public static final int IMP = 5;
  public static final int EXISTS = 20;
  public static final int MOD = 17;
  public static final int NEQ = 8;
  public static final int EQ = 7;
  public static final int LBRACK = 28;
  public static final int COLON = 35;
  public static final int UNION = 24;
  public static final int LBRACE = 31;
  public static final int RBRACK = 27;
  public static final int EQUIV = 6;
  public static final int NEXISTS = 21;
  public static final int RBRACE = 32;
  public static final int LEQ = 12;
  public static final int DIFF = 25;
  public static final int FALSE = 37;
  public static final int GT = 9;
}

