
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jun 01 03:03:59 EDT 2016
//----------------------------------------------------

package ltlparser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FORALL = 23;
  public static final int MULT = 20;
  public static final int EMPTY = 47;
  public static final int STR = 46;
  public static final int FLTL_UNTIL = 5;
  public static final int SUBEQSET = 31;
  public static final int LPAREN = 37;
  public static final int MINUS = 19;
  public static final int RPAREN = 36;
  public static final int NOT = 9;
  public static final int AND = 7;
  public static final int LT = 15;
  public static final int NIN = 28;
  public static final int FLTL_ALWAYS = 2;
  public static final int IN = 27;
  public static final int OR = 8;
  public static final int BOOL = 42;
  public static final int COMMA = 40;
  public static final int DIV = 22;
  public static final int GEQ = 16;
  public static final int NUM = 45;
  public static final int PLUS = 18;
  public static final int DOT = 41;
  public static final int EOF = 0;
  public static final int FLTL_SOMETIMES = 3;
  public static final int FLTL_WKUNTIL = 6;
  public static final int error = 1;
  public static final int IMP = 10;
  public static final int EXISTS = 24;
  public static final int MOD = 21;
  public static final int NEQ = 13;
  public static final int EQ = 12;
  public static final int FLTL_NEXT = 4;
  public static final int LBRACK = 35;
  public static final int SUBSET = 29;
  public static final int UNION = 32;
  public static final int LBRACE = 38;
  public static final int RBRACK = 34;
  public static final int EQUIV = 11;
  public static final int NEXISTS = 25;
  public static final int ID_UPCASE = 43;
  public static final int RBRACE = 39;
  public static final int SCOPE = 26;
  public static final int LEQ = 17;
  public static final int NSUBSET = 30;
  public static final int ID_LOWCASE = 44;
  public static final int DIFF = 33;
  public static final int GT = 14;
}

