
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Feb 13 13:14:51 EST 2016
//----------------------------------------------------

package pipe.core.expression.statespec.parser;

/**
 * CUP generated class containing symbol constants.
 */
public class sym {
  /* terminals */
  public static final int RPAREN = 5;
  public static final int NOT = 4;
  public static final int AND = 2;
  public static final int error = 1;
  public static final int STR = 7;
  public static final int LPAREN = 6;
  public static final int OR = 3;
  public static final int EOF = 0;
}

